### ISSUE TITLE
Installation leads to "Bad Gateway"

### ISSUE THREAD

**Issue by GZangl** [shihjay2/nosh3#1]
Dear Shihjay,
I followed your instructions to install Nosh, but even though all containers are running, I can't start the website.
Here is a copy of the server command prompt:
user@ip-10-0-9-33:/var/www/nosh$ sudo docker compose up -d
[+] Running 5/5
 ⠿ Network nosh_default  Created                                                                                                                                          0.1s
 ⠿ Container couchdb     Started                                                                                                                                          1.9s
 ⠿ Container nosh        Started                                                                                                                                          2.2s
 ⠿ Container watchtower  Started                                                                                                                                          1.5s
 ⠿ Container router      Started                                                                                                                                          2.2s
user@ip-10-0-9-33:/var/www/nosh$ curl http://localhost/start
Bad Gateway user@ip-10-0-9-33:/var/www/nosh$

As you can see, I get a"Bad Gateway" response.

Env file ist standard:
COUCHDB_URL=http://127.0.0.1:5984
COUCHDB_USER=admin
COUCHDB_PASSWORD=mypassword
COUCHDB_ENCRYPT_PIN=mypin
INSTANCE=local
NOSH_ROLE=patient
AUTH=magic
MAGIC_API_KEY=my_magic_api_key
USPSTF_KEY=my_uspstf_key
UMLS_KEY=my_umls_key
  
 Any idea, what the problem could be?
Thanks for your help
Georg

**Comment by shihjay2** [comment]
Please check if port 80 and 443 are open and not in use (noted your install directory (/var/www) suggests you might have Apache running.
What is the docker-compose.yml file you have?
Depending on what the docker-compose.yml file configuration, you may need to change the COUCHDB_URL to http://couchdb:5984
with your env file, the parameters are the minimum set for a NOSH_ROLE of provider, not patient.

**Comment by shihjay2** [comment]
Fixed with b473fb4dcb558ee9edf114dfc404920971d4ca3a
