### ISSUE TITLE
support for arm64/v8

### ISSUE THREAD

**Issue by devsdocs** [shihjay2/nosh3#5]
got this error

> nosh The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by shihjay2** [comment]
Added new Docker image platform for linux/amd64/v8 in commit [bfed959](https://github.com/shihjay2/nosh3/commit/bfed9593f13b60f106f8a9a5ef8a718bfc8f3c1f).

**Comment by devsdocs** [comment]
ty
